### ISSUE TITLE
[BUG] - Wrong name-label alias  in instance_info module

### ISSUE THREAD

**Issue by samerbahri98** [vultr/ansible-collection-vultr#105]
**Describe the bug**
the documentation for the instance_info indicate that name is an alias for label, however currently it is behaving as an alias for region instead

**To Reproduce**
1. Run this playbook
```yaml
---
- name: Instance
  hosts: localhost
  tasks:
    - name: Deploy Instance
      vultr.cloud.instance:
        label: foo
        region: fra
        plan: vc2-1c-1gb
        os: Ubuntu 22.04 LTS x64

    - name: Get Instance
      vultr.cloud.instance_info:
        name: foo
      register: results

    - debug:
        var: results

    - name: Get Instance
      vultr.cloud.instance_info:
        name: fra
      register: results

    - debug:
        var: results
```
**Additional context**

A pull request should be linked to this issue to fix this trivial bug
