### ISSUE TITLE
[BUG] - Object storage requires tier specification

### ISSUE THREAD

**Issue by jasites** [vultr/ansible-collection-vultr#135]
**Describe the bug**
Object storage subscriptions recently added tiers and made specifying a tier a requirement upon creation

**To Reproduce**
```
- name: test create object storage cluster 1
  vultr.cloud.object_storage:
    label: "{{ vultr_object_storage_name }}"
    cluster: "{{ vultr_object_storage_cluster1 }}"
```

**Expected behavior**
Object storage subscription created

**Additional context**

```
2025-04-07T12:47:54.1977919Z TASK [object_storage : test create object storage cluster 1] *******************
2025-04-07T12:47:55.1131205Z [0;31mfatal: [testhost]: FAILED! => {"changed": false, "fetch_url_info": {"body": "{\"error\":\"Invalid tier specified for this location\",\"status\":400}", "connection": "close", "content-type": "application/json", "date": "Mon, 07 Apr 2025 12:47:55 GMT", "msg": "HTTP Error 400: Bad Request", "server": "nginx", "status": 400, "strict-transport-security": "max-age=63072000", "transfer-encoding": "chunked", "url": "https://api.vultr.com/v2/object-storage", "x-content-type-options": "nosniff", "x-frame-options": "DENY", "x-robots-tag": "noindex,noarchive", "x-user": "ansible+opensource@vultr.com"}, "msg": "Failure while calling the Vultr API v2 with POST for \"/object-storage\"."}[0m
```
