### ISSUE TITLE
[BUG] - dns_domain requires IP for state=present

### ISSUE THREAD

**Issue by TheDavidFactor** [vultr/ansible-collection-vultr#140]
**Describe the bug**
dns_domain module requires ip for state=present, but the Vultr API does not require an ip and creating an empty domain without an initial ip value is completely valid.

**To Reproduce**
1) Add an ansible task:
```
- name: "Create domain: {{ domain }}"
  vultr.cloud.dns_domain:
    name: "{{ domain }}"
    state: present

```
2) Run the task, and get the error:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: ip"}`

**Expected behavior**
It should create an empty domain entry

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
 - OS: AlmaLinux 9.x
 - Language Version: ansible [core 2.14.17]

**Additional context**

Simply commenting out the requirement in the module worked. I'm creating a pull request against this issue
