### ISSUE TITLE
inventory plugin uses vultr label to connect, rather than main_ip or hostname

### ISSUE THREAD

**Issue by gbot** [vultr/ansible-collection-vultr#52]
While the vultr plugin dynamically builds an inventory for vultr instances, when actually connecting to run ansible tasks the `vultr_label` is used, rather than `main_ip` or `hostname`, so unless the label happens to be a domain or IP that resolves to the server, the connection fails.

This is my 'vultr.yml' inventory:
```
plugin: vultr.cloud.vultr
api_key: XXX
attributes: disk,features,hostname,id,label,main_ip,os,plan,power_status,ram,region,server_status,status,tags,vcpu_count

keyed_groups:
  # Group by "region"
  - key: vultr_region | lower
    separator: ''
    prefix: region_
  # Group by "tags"
  - key: vultr_tags | lower
    separator: ''
    prefix: ''
```

when I run `ansible-inventory --list` I get a dynamic inventory as expected:

```
            "domain1.org": {
                "ansible_become": true,
                "ansible_user": "testadmin",
                "vultr_disk": 55,
                "vultr_features": [],
                "vultr_hostname": "domain1.org",
                "vultr_id": "XXX",
                "vultr_label": "mylabel",
                "vultr_main_ip": "XXX",
                "vultr_os": "Ubuntu 20.04 LTS x64",
                "vultr_plan": "vc2-1c-2gb",
                "vultr_power_status": "running",
                "vultr_ram": 2048,
                "vultr_region": "syd",
                "vultr_server_status": "ok",
                "vultr_status": "active",
                "vultr_tags": [
                    "mytag1"
                ],
                "vultr_vcpu_count": 1
            },
```

however, running a task fails if the label doesn't resolve to the server. Or, as in one case I have, the domain in the `vultr_label` uses CloudFlare for DNS, so doesn't resolve to the server directly and no port 22 connection is available. If Ansible was using `main_ip` or `ansible_host` it would work.

**To Reproduce**
1. Create a dynamic inventory of a Vultr account, using above example
2. Ensure that at least one server has a "label" that is NOT a domain or IP that would resolve to the server
3. run a test task such as `ansible -a uptime all`
4. connections will fail for any host whose "label" doesn't resolve to the server.

```
domain1.org | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname mylabel: Name or service not known",
    "unreachable": true
}
```

**Expected behavior**
Ansible should connect via SSH using `main_ip` or `ansible_host` and run tasks as usual.

 - ansible 2.9.6

**Comment by resmo** [comment]
Thanks @gbot for the report. 

I don't think it's necessarily a bug, but certainly a documentation issue.  We will look into it.
In the meantime, we suggest setting `ansible_host` with compose:

```yaml
plugin: vultr.cloud.vultr
compose:
  ansible_host: vultr_main_ip
```
