### ISSUE TITLE
[BUG] - The api key is not being read by the plugin.

### ISSUE THREAD

**Issue by Hickory420** [vultr/ansible-collection-vultr#60]
**Describe the bug**
The `api_key` value is not being recognised

**To Reproduce**
`./vultr.yaml`
```yaml
---
plugin: vultr.cloud.vultr
api_key: abc123
```

`view_plans.yaml`
```yaml
---
- name: View the plans
  hosts: localhost
  tasks:
    - name: Gather Vultr regions information
      vultr.cloud.region_info:
      register: region

    - name: Print the list of countries
      ansible.builtin.debug:
        var: item.country
```

**Expected behavior**
List the plans's countries

**Screenshots**
```
$ ansible-playbook view_plans.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

PLAY [View the plans] **********************************************************************************************

TASK [Gathering Facts] *********************************************************************************************
ok: [localhost]

TASK [Gather Vultr regions information] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: api_key"}

PLAY RECAP *********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```
**Desktop (please complete the following information where applicable:**
 - OS: MacOS 12.6 Monterey (M1)
 - Ansible Version: core 2.14.2
```
$ brew list ansible --version
ansible 7.2.0
chris@cerebro:test_vultr $ ansible-galaxy collection list vultr.cloud

# /opt/homebrew/lib/python3.11/site-packages/ansible_collections
Collection  Version
----------- -------
vultr.cloud 1.7.0  

# /Users/${USER}/.ansible/collections/ansible_collections
Collection  Version
----------- -------
vultr.cloud 1.7.0  
```
**Additional context**

I have tried many iterations of yaml and ini files for the vultr plugin, but nothing seems to be working.
I have read the [collections module page|https://docs.ansible.com/ansible/latest/collections/vultr/cloud/vultr_inventory.html#ansible-collections-vultr-cloud-vultr-inventory] and it says 

```
# File endings vultr{,-{hosts,instances}}.y{,a}ml
# All configuration done via environment variables:
plugin: vultr.cloud.vultr
api_key: '{{ lookup("pipe"), "./get_vultr_api_key.sh" }}'
```
I replaced the Jinja with the actual API Key. I named it (as above) `vultr.yaml`

I have no idea how to get ansible to recognise the `api_key` variable... I have been trying for a few hours now and I have exhausted all avenues. I have even gone as far as debugging `plugins/inventory/vultr.py` to see where *exactly* this `api_key` variable is read from, but I've only just started... I thought I'd write this first. 

Any help would be immensely appreciated.
Cheers.

**Comment by resmo** [comment]
Hi @Hickory420 

Ansible has a few plugin types, in vultr we implemented 2 types: inventory plugin and module (task plugin).

The config in ./vultr.yaml, e.g.

```yaml
plugin: vultr.cloud.vultr
api_key: your key
```
is _only_ for the inventory plugin, further you would need to _enable_ this plugin in your `ansible.cfg` in your project roots direcotory: 

```ini
[inventory]
enable_plugins = host_list, script, auto, yaml, ini, toml, vultr.cloud.vultr
```

To test it, you could run:

`ansible-inventory -i vultr.yml --list`

and you should get a list of all vultr instances, to test connection, you have to tell the plugin how to connect to the instances if you don't want to use the label name as a DNS target (this is in the docs of the plugin `ansible-doc -t inventory vultr.cloud.vultr`)

```yaml
plugin: vultr.cloud.vultr
api_key: your key
compose:
  ansible_host: vultr_main_ip
```
after that you will be able to "ping" (ssh into your VMs and test connection) using:

```
ansible -m ping -i vultr.yml -u root all 
```

If you want to use the modules to create instances, see plans, regions and so on, the API key must be provided again (https://docs.ansible.com/ansible/latest/collections/vultr/cloud/region_info_module.html#parameter-api_key) to this plugin type. This could be achieved in few different ways (not vultr specific) but one way would be to put it into a `group_vars` variable and pass it in the tasks as an argument: 

```yaml
---
- name: View the regions
  hosts: localhost
  vars:
    # this would go into group_vars/all.yml
     vultr_api_key: my key
  tasks:
    - name: Gather Vultr regions information
      vultr.cloud.region_info:
         api_key: "{{ vultr_api_key }}"
      register: region

    - name: Print the gathered information
        ansible.builtin.debug:
        var: result.vultr_region_info
```

NOTE: Another way to provide the vultr api key to all plugin types is using an environment variable:  

```
$ export VULTR_API_KEY=my key
ansible-inventory -i vultr.yml --list
```

I hope my explanation solved the issue.

**Comment by Hickory420** [comment]
> in vultr we implemented 2 types: inventory plugin and module (task plugin).

🤯 

Thank you very much for pointing me in the right direction. I would like to avoid setting the environment variable for the `VULTR_API_KEY` as I would like to keep it encrypted within ansible.

This is what I ended up with (for now)
```
.
├── roles
│   └── common
│       ├── tasks
│       │   └── main.yaml
│       └── vars
│           └── main.yaml
└── site.yaml
```

`roles/common/tasks/main.yaml`
```yaml
---
- name: Setting Vars
  ansible.builtin.include_vars: main.yaml

- name: Gather Vultr regions information
  vultr.cloud.region_info:
    api_key: "{{ api_key }}"
  register: region

- name: Print syd region information
  ansible.builtin.debug:
    var: "{{ region }}"
  loop: "{{ region.vultr_region_info }}"
  when:
    - item.country == "AU"
    - item.id == "syd"
```

`roles/common/vars/main.yaml`
```yaml
---
plugin: vultr.cloud.vultr
api_key: abc123
compose:
  ansible_host: vultr_main_ip
```

`site.yaml`
```yaml
- name: Main Play
  hosts: localhost
  roles:
    - { role: common, tags: always }
```

And I call it with
```
ansible-playbook site.yaml
```

I can confirm the `api_key` variable gets carried across multiple roles. 

Thank you once again for you help.
