### ISSUE TITLE
Typo in `instance_info` examples

### ISSUE THREAD

**Issue by Hickory420** [vultr/ansible-collection-vultr#72]
Hello, I just wanted to point out a typo in
https://docs.ansible.com/ansible/latest/collections/vultr/cloud/instance_info_module.html#examples
```yaml
- name: Get Vultr instance infos of region ams
  vultr.cloud.instances_info:
    region: ams

- name: Get Vultr instance infos of a single host
  vultr.cloud.instances_info:
    label: myhost

- name: Get all Vultr instance infos
  vultr.cloud.instances_info:
  register: results

- name: Print the gathered infos
  ansible.builtin.debug:
    var: results.vultr_instance_info
```
The issue being there is an `s` in ` vultr.cloud.instances_info:`, where it should be ` vultr.cloud.instance_info:`

Thank you for this ansible collection!
