### ISSUE TITLE
[Feature] - vultr_gateway_v4 not set in hostvars; gateway_v4 appears in vultr.cloud.instance_info

### ISSUE THREAD

**Issue by TheSemicolons** [vultr/ansible-collection-vultr#91]
**Describe the bug**
The Ansible `hostvars` variable is missing `vultr_gateway_v4`.

**To Reproduce**

inventory.vultr.yml
```        
plugin: vultr.cloud.vultr
api_key: "[REMOVED]"
compose:
  ansible_host: vultr_internal_ip or vultr_v6_main_ip or vultr_main_ip
keyed_groups:
  - key: vultr_tags | lower
    prefix: ''
    separator: ''
strict: true
```
info.yml
```
---
- name: Info playbook
  hosts:
    - localhost
  tasks:
    - name: hostvars
      ansible.builtin.debug:
        var: hostvars
```

Debug:
```
            "vultr_hostname": "[REMOVED]",
            "vultr_id": "[REMOVED]",
            "vultr_internal_ip": "[REMOVED]",
            "vultr_label": "[REMOVED]",
            "vultr_main_ip": "[REMOVED]",
            "vultr_plan": "[REMOVED]",
            "vultr_region": "[REMOVED]",
            "vultr_tags": [
                "[REMOVED]"
            ],
            "vultr_v6_main_ip": "[REMOVED]"
```

**Expected behavior**
A variable for `vultr_gateway_v4` with the value of the IPv4 gateway.

**Desktop (please complete the following information where applicable:**
 - OS: OpenBSD 7.2
 - Vultr Collection Version: 1.10.0
 - Ansible Version:
 ```
 ansible [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Dec 16 2022, 16:48:31) [Clang 13.0.0 ]
  jinja version = 3.1.2
  libyaml = True
```

**Notes**
`gateway_v4` does show up when using `vultr.cloud.instance_info`
