### ISSUE TITLE
[Feature] - automatic private network set up with enable_vpc: true|false

### ISSUE THREAD

**Issue by timdiggins** [vultr/ansible-collection-vultr#94]
**Is your feature request related to a problem? Please describe.**

I'm migrating from old "vultr_server" (https://docs.ansible.com/ansible/2.8/modules/vultr_server_module.html) ansible (late to the party) and looking for an equivalent to `private_network_enabled: true`

This is mostly provided by api v2 `enable_vpc` or `enable_vpc2` (https://www.vultr.com/api/#tag/instances/operation/create-instance)

**Describe the solution you'd like**

A simple way to setup default vpc on creating an instance and use `enable_vpc` or `enable_vpc2` on the api

**Describe alternatives you've considered**

Manual set up of vpcs - however I just need one default vpc  (seems like the simplest use case) and this is what the api provides

**Comment by resmo** [comment]
Hi @timdiggins 

In terms of idempotency, `enable_vpc/enable_vpc2` is tricky for the following reasons:

1. users have no control over the IP subnet and CIDR
2. if a user ever wants to have a 2nd VPC, it would no longer work

Therefore, our suggestion is to define a VPC as follows:

```yaml

- name: Ensure a VPC is present
  vultr.cloud.vpc:
    description: default
    subnet: 10.99.1.0
    subnet_mask: 24
    region: ams

- name: Create an instance using OS
  vultr.cloud.instance:
    label: web1
    hostname: my-hostname
    os: Debian 12 x64 (bookworm)
    firewall_group: my firewall group
    plan: vc2-1c-2gb
    ssh_keys:
      - my ssh key
    vpcs:
      - default
    region: ams

```

Would this be an option?
